### ISSUE TITLE
Teku

### ISSUE THREAD

**Issue by madhancr** [attestantio/dirk#1]
Does Dirk work with Teku? Can you show how to use this tool with Teku and Prysm for Medella?

**Comment by mcdee** [comment]
We have plans to talk to the client teams regarding use of Dirk directly with their validator clients, but there is no direct integration available today.

**Comment by mcdee** [comment]
[Vouch](https://github.com/attestantio/vouch) can talk to Teku via the now-standard REST API, and use Dirk as its signer.  Details on how to use Vouch withe Teku can be found in the link provided.
