### ISSUE TITLE
Pruning slashing protection storage

### ISSUE THREAD

**Issue by freshfab** [attestantio/dirk#13]
Hey! I'm wondering how to handle pruning of the database for information on slashing protection since dirk doesn't provide any options for it.

First, I'd like to know whether there's a reason for not having such an option? If not, up to which point is it safe to prune the database then?

Thanks!

**Comment by mcdee** [comment]
The internal data does not grow, as it contains only the information about the latest attestations and block proposals.  However, the on-disk format can grow over time.  I will look in to how best to provide the database maintenance process (either internally as a dirk command or externally as a procedure) and update the repository accordingly.

**Comment by mcdee** [comment]
Turns out that this can be carried out in-process. #14 addresses this issue.
