### ISSUE TITLE
Add possibility to load credentials automatically for majordomo asm/gsm 

### ISSUE THREAD

**Issue by p2p-sergey-y** [attestantio/dirk#29]
Google Cloud and AWS both support to load credential via metadata service without any interaction if IAM roles/sa are attached to VM. 

Current it's impossible to use because dirk pass only [credentialPath](https://github.com/attestantio/dirk/blob/d5c13dbc36dcb6486fda451b6cd00970e364cbf3/main.go#L575), and majordomo strictly use only that too ([gsm](https://github.com/wealdtech/go-majordomo/blob/master/confidants/gsm/service.go#L87), [asm](https://github.com/wealdtech/go-majordomo/blob/master/confidants/asm/service.go#L97)).
I think it could be a good idea to make the default way getting credentials from metadata service work

**Comment by selfuryon** [comment]
It turns out that ASM support that right now due to non-mandatory path config option, which passed like empty string `""`, and GSM was fixed by https://github.com/attestantio/dirk/pull/31, so I close this issue
