### ISSUE TITLE
dirk vs web3signer vs keyvault vs charon

### ISSUE THREAD

**Issue by ybstaked** [attestantio/dirk#48]
Would love to see docs or example setups explaining differences, nuiances and tradeoffs between dirk, web3signer, charon and keyvault!

* https://www.attestant.io/posts/introducing-dirk/
* https://docs.web3signer.consensys.net/HowTo/Store-Keys-Vaults/Use-Hashicorp
* https://docs.obol.tech/docs/int/key-concepts
* https://github.com/bloxapp/key-vault

**Comment by mcdee** [comment]
We're not familiar with the other apps so cannot provide a detailed analysis of the differences.
